apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: okteto.dev/svc-trainings
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: auth-secret
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
