"""add scores

Revision ID: 5c420357e3b3
Revises: d9f252b4b7b5
Create Date: 2023-05-16 21:58:22.830635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c420357e3b3"
down_revision = "d9f252b4b7b5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("training_id", sa.Integer(), nullable=False),
        sa.Column("author", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["training_id"],
            ["trainings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("training_scores", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_training_scores_id"), ["id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("training_scores", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_training_scores_id"))

    op.drop_table("training_scores")
    # ### end Alembic commands ###
