"""add missing fields

Revision ID: afe7ae9f34cc
Revises: 1c72412e20e8
Create Date: 2023-05-01 21:09:58.332662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "afe7ae9f34cc"
down_revision = "1c72412e20e8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("training_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["training_id"],
            ["trainings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("training_goals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_training_goals_id"), ["id"], unique=False
        )

    op.create_table(
        "training_multimedias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("training_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["training_id"],
            ["trainings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("training_multimedias", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_training_multimedias_id"), ["id"], unique=False
        )

    with op.batch_alter_table("trainings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("author", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("blocked", sa.Boolean(), nullable=False))
        batch_op.alter_column(
            "title", existing_type=sa.VARCHAR(length=30), nullable=False
        )
        batch_op.alter_column(
            "description", existing_type=sa.VARCHAR(length=500), nullable=False
        )
        batch_op.alter_column(
            "type", existing_type=sa.VARCHAR(length=7), nullable=False
        )
        batch_op.alter_column(
            "difficulty", existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trainings", schema=None) as batch_op:
        batch_op.alter_column(
            "difficulty", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "type", existing_type=sa.VARCHAR(length=7), nullable=True
        )
        batch_op.alter_column(
            "description", existing_type=sa.VARCHAR(length=500), nullable=True
        )
        batch_op.alter_column(
            "title", existing_type=sa.VARCHAR(length=30), nullable=True
        )
        batch_op.drop_column("blocked")
        batch_op.drop_column("author")

    with op.batch_alter_table("training_multimedias", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_training_multimedias_id"))

    op.drop_table("training_multimedias")
    with op.batch_alter_table("training_goals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_training_goals_id"))

    op.drop_table("training_goals")
    # ### end Alembic commands ###
