"""add goal.description and training.createdAt

Revision ID: d9f252b4b7b5
Revises: afe7ae9f34cc
Create Date: 2023-05-09 23:49:13.599089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d9f252b4b7b5"
down_revision = "afe7ae9f34cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("training_goals", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.String(length=300), nullable=False)
        )

    with op.batch_alter_table("trainings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("created_at", sa.DateTime(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trainings", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("training_goals", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
